### ISSUE TITLE
whats the difference between this and request-header-saml-service-provider ?

### ISSUE THREAD

**Issue by itewk** [chrisruffalo/ose-pivproxy#2]
@chrisruffalo  What is the difference of this project and https://github.com/openshift/request-header-saml-service-provider

**Comment by chrisruffalo** [comment]
@itewk it looks like the request-header-saml-service-provider provides a SAML proxy to the OpenShift's HTTP Auth. So you would need a SAML provider for that. It also doesn't seem to come with anything out of the box for converting to or running pods.

This project is specifically set up to:
a) create a (set of) pod(s) that run the entire stack necessary to authenticate PIV cards
b) provide that information to OpenShift via the RequestHeader authentication.

**Comment by itewk** [comment]
kk.
